name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # или master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Secrets
        env:
          # Явно передаем секреты в переменные окружения шага
          MY_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          MY_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          MY_USERNAME: ${{ secrets.TG_USERNAME }}
        run: |
          # Используем переменные среды (с символом $)
          sed -i "s|PROCESS_TG_BOT_TOKEN|$MY_BOT_TOKEN|g" index.html
          sed -i "s|PROCESS_TG_CHAT_ID|$MY_CHAT_ID|g" index.html
          sed -i "s|PROCESS_TG_USERNAME|$MY_USERNAME|g" index.html
