name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # или master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Inject Secrets
        run: |
          # Заменяем метки в файле на секреты из GitHub
          sed -i "s/PROCESS_TG_BOT_TOKEN/${{ secrets.TG_BOT_TOKEN }}/g" index.html
          sed -i "s/PROCESS_TG_CHAT_ID/${{ secrets.TG_CHAT_ID }}/g" index.html
          sed -i "s/PROCESS_TG_USERNAME/${{ secrets.TG_USERNAME }}/g" index.html
        # Укажите правильный путь к вашему файлу (например, js/config.js)

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # папка, которую нужно деплоить
          branch: gh-pages # ветка для деплоя
